### PR TITLE
Add normalized and normalized-fold varieties of match/find/rank

### PR DESCRIPTION
**Pull request by acaloiaro**
Add Unicode-normalized varieties of all existing functions. 
---
Unicode normalization approach inspired by https://blog.golang.org/normalization

### CODE REVIEW

**Comment by lithammer** [comment]
I will take a look at why Travis CI is failing. Or actually, I will probably just switch to GitHub Actions.

**Comment by lithammer** [comment]
I just merged #17 which switches to GitHub Actions for pull requests checks. Can you rebase to see if that solves the pull request check problem?

**Comment by acaloiaro** [comment]
@lithammer FYI I added a `pull_request` event to the github action so that checks run on pull requests from forks, as well as on merge. Looks like all tests are passing 🎉

**Comment by lithammer** [comment]
Everything looks in order. Thanks for contributing, this is definitely a nice thing! 👌

**Comment by lithammer** [comment]
I published a new [v1.1.0](https://github.com/lithammer/fuzzysearch/releases/tag/v1.1.0) release that contains this.

**Comment by acaloiaro** [comment]
@lithammer happy to contribute and thanks for the quick turnaround. Cheers!

**Pull request merged**
